// Generated by gencpp from file computer_vision/motor_throttle.msg
// DO NOT EDIT!


#ifndef COMPUTER_VISION_MESSAGE_MOTOR_THROTTLE_H
#define COMPUTER_VISION_MESSAGE_MOTOR_THROTTLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace computer_vision
{
template <class ContainerAllocator>
struct motor_throttle_
{
  typedef motor_throttle_<ContainerAllocator> Type;

  motor_throttle_()
    : left_motor(0.0)
    , right_motor(0.0)  {
    }
  motor_throttle_(const ContainerAllocator& _alloc)
    : left_motor(0.0)
    , right_motor(0.0)  {
  (void)_alloc;
    }



   typedef float _left_motor_type;
  _left_motor_type left_motor;

   typedef float _right_motor_type;
  _right_motor_type right_motor;





  typedef boost::shared_ptr< ::computer_vision::motor_throttle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::computer_vision::motor_throttle_<ContainerAllocator> const> ConstPtr;

}; // struct motor_throttle_

typedef ::computer_vision::motor_throttle_<std::allocator<void> > motor_throttle;

typedef boost::shared_ptr< ::computer_vision::motor_throttle > motor_throttlePtr;
typedef boost::shared_ptr< ::computer_vision::motor_throttle const> motor_throttleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::computer_vision::motor_throttle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::computer_vision::motor_throttle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::computer_vision::motor_throttle_<ContainerAllocator1> & lhs, const ::computer_vision::motor_throttle_<ContainerAllocator2> & rhs)
{
  return lhs.left_motor == rhs.left_motor &&
    lhs.right_motor == rhs.right_motor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::computer_vision::motor_throttle_<ContainerAllocator1> & lhs, const ::computer_vision::motor_throttle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace computer_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::computer_vision::motor_throttle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::computer_vision::motor_throttle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::computer_vision::motor_throttle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::computer_vision::motor_throttle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::computer_vision::motor_throttle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::computer_vision::motor_throttle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::computer_vision::motor_throttle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e3717ac8e9443aa62d7102a5860f5e7";
  }

  static const char* value(const ::computer_vision::motor_throttle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e3717ac8e9443aaULL;
  static const uint64_t static_value2 = 0x62d7102a5860f5e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::computer_vision::motor_throttle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "computer_vision/motor_throttle";
  }

  static const char* value(const ::computer_vision::motor_throttle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::computer_vision::motor_throttle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left_motor\n"
"float32 right_motor\n"
;
  }

  static const char* value(const ::computer_vision::motor_throttle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::computer_vision::motor_throttle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_motor);
      stream.next(m.right_motor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_throttle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::computer_vision::motor_throttle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::computer_vision::motor_throttle_<ContainerAllocator>& v)
  {
    s << indent << "left_motor: ";
    Printer<float>::stream(s, indent + "  ", v.left_motor);
    s << indent << "right_motor: ";
    Printer<float>::stream(s, indent + "  ", v.right_motor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMPUTER_VISION_MESSAGE_MOTOR_THROTTLE_H
