// Generated by gencpp from file computer_vision/motor_cmd.msg
// DO NOT EDIT!


#ifndef COMPUTER_VISION_MESSAGE_MOTOR_CMD_H
#define COMPUTER_VISION_MESSAGE_MOTOR_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace computer_vision
{
template <class ContainerAllocator>
struct motor_cmd_
{
  typedef motor_cmd_<ContainerAllocator> Type;

  motor_cmd_()
    : left_motor(0)
    , right_motor(0)  {
    }
  motor_cmd_(const ContainerAllocator& _alloc)
    : left_motor(0)
    , right_motor(0)  {
  (void)_alloc;
    }



   typedef int32_t _left_motor_type;
  _left_motor_type left_motor;

   typedef int32_t _right_motor_type;
  _right_motor_type right_motor;





  typedef boost::shared_ptr< ::computer_vision::motor_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::computer_vision::motor_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct motor_cmd_

typedef ::computer_vision::motor_cmd_<std::allocator<void> > motor_cmd;

typedef boost::shared_ptr< ::computer_vision::motor_cmd > motor_cmdPtr;
typedef boost::shared_ptr< ::computer_vision::motor_cmd const> motor_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::computer_vision::motor_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::computer_vision::motor_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::computer_vision::motor_cmd_<ContainerAllocator1> & lhs, const ::computer_vision::motor_cmd_<ContainerAllocator2> & rhs)
{
  return lhs.left_motor == rhs.left_motor &&
    lhs.right_motor == rhs.right_motor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::computer_vision::motor_cmd_<ContainerAllocator1> & lhs, const ::computer_vision::motor_cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace computer_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::computer_vision::motor_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::computer_vision::motor_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::computer_vision::motor_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::computer_vision::motor_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::computer_vision::motor_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::computer_vision::motor_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::computer_vision::motor_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a65b38dd0991191156f3432b9d44007";
  }

  static const char* value(const ::computer_vision::motor_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a65b38dd0991191ULL;
  static const uint64_t static_value2 = 0x156f3432b9d44007ULL;
};

template<class ContainerAllocator>
struct DataType< ::computer_vision::motor_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "computer_vision/motor_cmd";
  }

  static const char* value(const ::computer_vision::motor_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::computer_vision::motor_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 left_motor\n"
"int32 right_motor\n"
;
  }

  static const char* value(const ::computer_vision::motor_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::computer_vision::motor_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_motor);
      stream.next(m.right_motor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::computer_vision::motor_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::computer_vision::motor_cmd_<ContainerAllocator>& v)
  {
    s << indent << "left_motor: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_motor);
    s << indent << "right_motor: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_motor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMPUTER_VISION_MESSAGE_MOTOR_CMD_H
