// Generated by gencpp from file computer_vision/motor_throttle.msg
// DO NOT EDIT!


#ifndef COMPUTER_VISION_MESSAGE_MOTOR_THROTTLE_H
#define COMPUTER_VISION_MESSAGE_MOTOR_THROTTLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace computer_vision
{
template <class ContainerAllocator>
struct motor_throttle_
{
  typedef motor_throttle_<ContainerAllocator> Type;

  motor_throttle_()
    : header()
    , left_motor(0.0)
    , right_motor(0.0)  {
    }
  motor_throttle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_motor(0.0)
    , right_motor(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _left_motor_type;
  _left_motor_type left_motor;

   typedef float _right_motor_type;
  _right_motor_type right_motor;





  typedef boost::shared_ptr< ::computer_vision::motor_throttle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::computer_vision::motor_throttle_<ContainerAllocator> const> ConstPtr;

}; // struct motor_throttle_

typedef ::computer_vision::motor_throttle_<std::allocator<void> > motor_throttle;

typedef boost::shared_ptr< ::computer_vision::motor_throttle > motor_throttlePtr;
typedef boost::shared_ptr< ::computer_vision::motor_throttle const> motor_throttleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::computer_vision::motor_throttle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::computer_vision::motor_throttle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::computer_vision::motor_throttle_<ContainerAllocator1> & lhs, const ::computer_vision::motor_throttle_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_motor == rhs.left_motor &&
    lhs.right_motor == rhs.right_motor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::computer_vision::motor_throttle_<ContainerAllocator1> & lhs, const ::computer_vision::motor_throttle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace computer_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::computer_vision::motor_throttle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::computer_vision::motor_throttle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::computer_vision::motor_throttle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::computer_vision::motor_throttle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::computer_vision::motor_throttle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::computer_vision::motor_throttle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::computer_vision::motor_throttle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "810a90b3c92332e7051784244ee24b0c";
  }

  static const char* value(const ::computer_vision::motor_throttle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x810a90b3c92332e7ULL;
  static const uint64_t static_value2 = 0x051784244ee24b0cULL;
};

template<class ContainerAllocator>
struct DataType< ::computer_vision::motor_throttle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "computer_vision/motor_throttle";
  }

  static const char* value(const ::computer_vision::motor_throttle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::computer_vision::motor_throttle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 left_motor\n"
"float32 right_motor\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::computer_vision::motor_throttle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::computer_vision::motor_throttle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_motor);
      stream.next(m.right_motor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_throttle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::computer_vision::motor_throttle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::computer_vision::motor_throttle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_motor: ";
    Printer<float>::stream(s, indent + "  ", v.left_motor);
    s << indent << "right_motor: ";
    Printer<float>::stream(s, indent + "  ", v.right_motor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMPUTER_VISION_MESSAGE_MOTOR_THROTTLE_H
